---
self-hosted-runner:
  # Labels of self-hosted runner in array of strings.
  labels: 
    - botanix-actions-runner-vm-1
    - image-builder
    - botanix-actions-runner
    - k8-runners
    - binary-builder
# Configuration variables in array of strings defined in your repository or
# organization. `null` means disabling configuration variables check.
# Empty array means no configuration variable is allowed.
config-variables: null
