[build]
pre-build = [
  "apt-get update && apt-get install --assume-yes --no-install-recommends build-essential llvm-dev protobuf-compiler gcc pkg-config libprotobuf-dev libclang-6.0-dev clang-6.0 curl", # install system deps
  "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain 1.88.0 ",                                       # rustup
  ". \"$HOME/.cargo/env\" && rustup target add x86_64-unknown-linux-gnu"                                                                       # add target
]

[build.env]
passthrough = ["JEMALLOC_SYS_WITH_LG_PAGE"]
