[build]
pre-build = [
  "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y",
  "apt-get update && apt-get install --assume-yes --no-install-recommends build-essential llvm-dev protobuf-compiler gcc pkg-config libprotobuf-dev libclang-6.0-dev clang-6.0 curl", # install system deps                                                                    # add target
]

[build.env]
passthrough = ["JEMALLOC_SYS_WITH_LG_PAGE"]
