[cov_botanix_btc_server]
name = "Botanix Btc-Server Coverage Analysis"
packages = ["btc-server"]
all-features = true
run-types = ["Lib", "Tests"]
timeout = "120s"
color = "Always"
locked = true
count = true
no-dead-code = true
fail-immediately = true
skip-clean = true
engine = "Llvm"
#fail-under = 80


[cov_botanix_fed_utils]
name = "Botanix Federation Utils Coverage Analysis"
packages = ["federation-utils-cli"]
all-features = true
run-types = ["Tests"]
timeout = "120s"
color = "Always"
locked = true
count = true
no-dead-code = true
fail-immediately = true
skip-clean = true
engine = "Llvm"
#fail-under = 80


[cov_botanix_reth]
name = "Botanix Reth Coverage Analysis"
packages = ["reth"]
#all-features = true
run-types = ["Lib", "Tests"]
timeout = "120s"
color = "Always"
locked = true
count = true
no-dead-code = true
fail-immediately = true
skip-clean = true
engine = "Llvm"
#fail-under = 80


[report]
output-dir = "./cov-reports"
out = ["Html", "Xml"]
