{
 "title": "Btc-server Metrics",
 "tags": [ "btc-server" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "btc_chain",
    "query": {
     "query": "label_values(total_received_round1_dkg_packages,btc_chain)"
    }
   },
   {
    "name": "self_id",
    "query": {
     "query": "label_values(total_received_round1_dkg_packages,self_id)"
    }
   },
   {
    "name": "signing_session_id",
    "query": {
     "query": "label_values(round1_signing_throughput,signing_session_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Round1 Dkg Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "round1_dkg_throughput{btc_chain=~\"$btc_chain\", self_id=~\"$self_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Round2 Dkg Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "round2_dkg_throughput{btc_chain=~\"$btc_chain\", self_id=~\"$self_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Round1 Dkg Package Size Bytes Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "round1_dkg_package_size_bytes_sum{btc_chain=~\"$btc_chain\", self_id=~\"$self_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Round2 Dkg Package Size Bytes Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "round2_dkg_package_size_bytes_sum{btc_chain=~\"$btc_chain\", self_id=~\"$self_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Round1 Dkg Latency Millisecs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "round1_dkg_latency_secs_bucket{btc_chain=~\"$btc_chain\", self_id=~\"$self_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Round2 Dkg Latency Millisecs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "round2_dkg_latency_secs_bucket{btc_chain=~\"$btc_chain\", self_id=~\"$self_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total  Received Round1 Dkg Packages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "total_received_round1_dkg_packages{btc_chain=~\"$btc_chain\", self_id=~\"$self_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total  Received Round2 Dkg Packages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "total_received_round2_dkg_packages{btc_chain=~\"$btc_chain\", self_id=~\"$self_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Signing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true
  },
  {
   "title": "Round1 Signing Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "round1_signing_throughput{btc_chain=~\"$btc_chain\", self_id=~\"$self_id\", signing_session_id=~\"$signing_session_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Round2 Signing Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "round2_signing_throughput{btc_chain=~\"$btc_chain\", self_id=~\"$self_id\", signing_session_id=~\"$signing_session_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Round1 Signing Package Size Bytes Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "round1_signing_package_size_bytes_sum{btc_chain=~\"$btc_chain\", self_id=~\"$self_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Round2 Signing Package Size Bytes Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "round2_signing_package_size_bytes_sum{btc_chain=~\"$btc_chain\", self_id=~\"$self_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total  Received Round1 Signing Packages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "total_received_round1_signing_packages{btc_chain=~\"$btc_chain\", self_id=~\"$self_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total  Received Round2 Signing Packages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "total_received_round2_signing_packages{btc_chain=~\"$btc_chain\", self_id=~\"$self_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Round1 Signing Latency Millisecs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "round1_signing_latency_secs_bucket{btc_chain=~\"$btc_chain\", self_id=~\"$self_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Round2 Signing Latency Millisecs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "round2_signing_latency_secs_bucket{btc_chain=~\"$btc_chain\", self_id=~\"$self_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total  Received Round1 Signing Packages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "total_received_round1_signing_packages{btc_chain=~\"$btc_chain\", self_id=~\"$self_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total  Received Round2 Signing Packages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "total_received_round2_signing_packages{btc_chain=~\"$btc_chain\", self_id=~\"$self_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Aborted Signing Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "total_aborted_signing_sessions{btc_chain=~\"$btc_chain\", self_id=~\"$self_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Finalized Signing Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "total_finalized_signing_sessions{btc_chain=~\"$btc_chain\", self_id=~\"$self_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "collapsed": true
  }
 ]
}