---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: botanix-jwt-hex
  namespace: testnet
spec:
  refreshInterval: 1h           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore   # kind of SecretStore
    name: botanix-cluster-secret-store           # name of the SecretStore (or kind specified)
  target:
    name: botanix-jwt-hex # name of the k8s Secret to be created
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: botanix-jwt-hex

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: botanix-bitcoin-server-v1-secret
  namespace: testnet
spec:
  refreshInterval: 1h           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore   # kind of SecretStore
    name: botanix-cluster-secret-store           # name of the SecretStore (or kind specified)
  target:
    name: botanix-bitcoin-server-v1-secret # name of the k8s Secret to be created
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: botanix-bitcoin-server-v1-secret
    remoteRef:
      key: botanix-bitcoin-server-v1-secret

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: botanix-poa-v1-bitcoin-secret
  namespace: testnet
spec:
  refreshInterval: 1h           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore   # kind of SecretStore
    name: botanix-cluster-secret-store           # name of the SecretStore (or kind specified)
  target:
    name: botanix-poa-v1-bitcoin-secret # name of the k8s Secret to be created
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: botanix-poa-v1-bitcoin-secret