{{- if (.Values.rethNode).enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ (.Values.rethNode).name  }}
  labels:
    {{- toYaml (.Values.rethNode).labels | nindent 8 }}
spec:
  type: {{ ((.Values.rethNode).service).type }}
  loadBalancerIP: {{ ((.Values.rethNode).service).LoadBalancerIP }}
  ports:
    {{- range ((.Values.rethNode).service).port }}
        - name: {{ .name }}
          port: {{ .port }}
          targetPort: {{ .targetPort }}
    {{- end }}
  selector:
    {{- toYaml (.Values.rethNode).labels | nindent 8 }}
{{- end }}