version: '3.7'

services:
  cometbft-node-1:
    container_name: cometbft-node-1
    build:
      context: .
      dockerfile: cometbft-local.Dockerfile
    hostname: cometbft-node-1
    environment:
      - MONIKER=cometbft-node-1
      - PERSISTENT_PEERS=
      - P2P_LADDR=tcp://0.0.0.0:26656
      - P2P_ALLOW_DUPLICATE_IP=true
      - PROXY_APP=kvstore
      - P2P_ADDR_BOOK_STRICT=false
      - RPC_LADDR=tcp://0.0.0.0:26657
    ports:
      - 26656:26656
      - 26657:26657
    volumes:
      - ./cometbft-local-1:/cometbft
    networks:
      - cometbft-local

  cometbft-node-2:
    container_name: cometbft-node-2
    build:
      context: .
      dockerfile: cometbft-local.Dockerfile
    hostname: cometbft-node-2
    environment:
      - MONIKER=cometbft-node-2
      - PERSISTENT_PEERS=
      - P2P_LADDR=tcp://0.0.0.0:26656
      - P2P_ALLOW_DUPLICATE_IP=true
      - PROXY_APP=kvstore
      - P2P_ADDR_BOOK_STRICT=false
      - RPC_LADDR=tcp://0.0.0.0:26657
    ports:
      - 26658:26656
      - 26659:26657
    volumes:
      - ./cometbft-local-2:/cometbft
    networks:
      - cometbft-local

networks:
  cometbft-local:
    name: cometbft-local
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
      driver: default
