{
 "title": "Reth",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "query_result(reth_info)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_info{instance=~\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Build Timestamp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_info{instance=~\"$instance\"}",
     "legendFormat": "{{build_timestamp}}"
    }
   ]
  },
  {
   "title": "Git SHA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_info{instance=~\"$instance\"}",
     "legendFormat": "{{git_sha}}"
    }
   ]
  },
  {
   "title": "Build Profile",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_info{instance=~\"$instance\"}",
     "legendFormat": "{{build_profile}}"
    }
   ]
  },
  {
   "title": "Target Triple",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_info{instance=~\"$instance\"}",
     "legendFormat": "{{target_triple}}"
    }
   ]
  },
  {
   "title": "Cargo Features",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_info{instance=~\"$instance\"}",
     "legendFormat": "{{cargo_features}}"
    }
   ]
  },
  {
   "title": "Connected peers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_network_connected_peers{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stage checkpoints",
   "type": "bargauge",
   "description": "The checkpoints mark the last block a stage can recover from in the case of a crash or shutdown of the node",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "reth_sync_checkpoint{instance=~\"$instance\"}",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Storage size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(reth_db_table_size{instance=~\"$instance\"})",
     "legendFormat": "Database"
    },
    {
     "expr": "sum(reth_db_freelist{instance=~\"$instance\"} * reth_db_page_size{instance=~\"$instance\"})",
     "legendFormat": "Freelist"
    },
    {
     "expr": "sum(reth_static_files_segment_size{instance=~\"$instance\"})",
     "legendFormat": "Static Files"
    },
    {
     "expr": "sum(reth_db_table_size{instance=~\"$instance\"}) + sum(reth_db_freelist{instance=~\"$instance\"} * reth_db_page_size{instance=~\"$instance\"}) + sum(reth_static_files_segment_size{instance=~\"$instance\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Sync progress (stage progress in %)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "reth_sync_entities_processed{instance=~\"$instance\"} / reth_sync_entities_total{instance=~\"$instance\"}",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Sync progress (stage progress as highest block number reached)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "reth_sync_checkpoint{instance=~\"$instance\"}",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }, "repeat": "instance" },
  {
   "title": "Average commit time",
   "type": "timeseries",
   "description": "The average commit time for database transactions. Generally, this should not be a limiting factor in syncing.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(reth_database_transaction_close_duration_seconds_sum{instance=~\"$instance\", outcome=\"commit\"}[$__rate_interval]) / rate(reth_database_transaction_close_duration_seconds_count{instance=~\"$instance\", outcome=\"commit\"}[$__rate_interval]) >= 0)",
     "legendFormat": "Commit time"
    }
   ]
  },
  {
   "title": "Commit time heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "avg(max_over_time(reth_database_transaction_close_duration_seconds{instance=~\"$instance\", outcome=\"commit\"}[$__rate_interval])) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Average transaction open time",
   "type": "timeseries",
   "description": "The average time a database transaction was open.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(reth_database_transaction_open_duration_seconds_sum{instance=~\"$instance\", outcome!=\"\"}[$__rate_interval]) / rate(reth_database_transaction_open_duration_seconds_count{instance=~\"$instance\", outcome!=\"\"}[$__rate_interval])) by (outcome, mode)",
     "legendFormat": "{{mode}}, {{outcome}}"
    }
   ]
  },
  {
   "title": "Max transaction open time",
   "type": "timeseries",
   "description": "The maximum time the database transaction was open.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(max_over_time(reth_database_transaction_open_duration_seconds{instance=~\"$instance\", outcome!=\"\", quantile=\"1\"}[$__interval])) by (outcome, mode)",
     "legendFormat": "{{mode}}, {{outcome}}"
    }
   ]
  },
  {
   "title": "Number of open transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(reth_database_transaction_open_total{instance=~\"$instance\"}) by (mode)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Max insertion operation time",
   "type": "timeseries",
   "description": "The maximum time the database transaction operation which inserts a large value took.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(max_over_time(reth_database_operation_large_value_duration_seconds{instance=~\"$instance\", quantile=\"1\"}[$__interval]) > 0) by (table)",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Database tables",
   "type": "piechart",
   "description": "The size of tables in the database",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_db_table_size{instance=~\"$instance\"}",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Database growth",
   "type": "timeseries",
   "description": "The size of the database over time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job) ( reth_db_table_size{instance=~\"$instance\"} )",
     "legendFormat": "Size ({{job}})"
    }
   ]
  },
  {
   "title": "Database pages",
   "type": "piechart",
   "description": "The type of the pages in the database:\n\n- **Leaf** pages contain KV pairs.\n- **Branch** pages contain information about keys in the leaf pages\n- **Overflow** pages store large values and should generally be avoided if possible",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) ( reth_db_table_pages{instance=~\"$instance\"} )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overflow pages by table",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "sort_desc(reth_db_table_pages{instance=~\"$instance\", type=\"overflow\"} != 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Freelist",
   "type": "timeseries",
   "description": "The number of pages on the MDBX freelist",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(reth_db_freelist{instance=~\"$instance\"}) by (job)",
     "legendFormat": "Pages ({{job}})"
    }
   ]
  },
  { "title": "Static Files", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Segments size",
   "type": "piechart",
   "description": "The size of segments in the static files",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_static_files_segment_size{instance=~\"$instance\"}",
     "legendFormat": "{{segment}}"
    }
   ]
  },
  {
   "title": "Entries per segment",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 70 },
   "targets": [
    {
     "expr": "reth_static_files_segment_entries{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Files per segment",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 70 },
   "targets": [
    {
     "expr": "reth_static_files_segment_files{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Static Files growth",
   "type": "timeseries",
   "description": "The size of the static files over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job) ( reth_static_files_segment_size{instance=~\"$instance\"} )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max writer commit time",
   "type": "timeseries",
   "description": "The maximum time the static files operation which commits a writer took.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(max_over_time(reth_static_files_jar_provider_write_duration_seconds{instance=~\"$instance\", operation=\"commit-writer\", quantile=\"1\"}[$__interval]) > 0) by (segment)",
     "legendFormat": "{{segment}}"
    }
   ]
  },
  { "title": "Stage: Execution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 }, "repeat": "instance" },
  {
   "title": "Gas processed",
   "type": "timeseries",
   "description": "The amount of gas processed by the execution stage in millions per second.\n\nNote: For mainnet, the block range 2,383,397-2,620,384 will be slow because of the 2016 DoS attack.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "Mgas/s" } },
   "targets": [
    {
     "expr": "rate(reth_sync_execution_mgas_processed_total{instance=~\"$instance\"}[30s])",
     "legendFormat": "Gas/s (30s)"
    },
    {
     "expr": "rate(reth_sync_execution_mgas_processed_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "Gas/s (1m)"
    },
    {
     "expr": "rate(reth_sync_execution_mgas_processed_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "Gas/s (5m)"
    },
    {
     "expr": "rate(reth_sync_execution_mgas_processed_total{instance=~\"$instance\"}[10m])",
     "legendFormat": "Gas/s (10m)"
    }
   ]
  },
  { "title": "Downloader: Headers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 }, "repeat": "instance" },
  {
   "title": "I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "reth_downloaders_headers_total_downloaded{instance=~\"$instance\"}",
     "legendFormat": "Downloaded"
    },
    {
     "expr": "reth_downloaders_headers_total_flushed{instance=~\"$instance\"}",
     "legendFormat": "Flushed"
    },
    {
     "expr": "rate(reth_downloaders_headers_total_downloaded{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Downloaded/s"
    },
    {
     "expr": "rate(reth_downloaders_headers_total_flushed{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Flushed/s"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Internal errors in the header downloader. These are expected to happen from time to time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(reth_downloaders_headers_timeout_errors{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Request timed out"
    },
    {
     "expr": "rate(reth_downloaders_headers_unexpected_errors{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Unexpected error"
    },
    {
     "expr": "rate(reth_downloaders_headers_validation_errors{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Invalid response"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "The number of connected peers and in-progress requests for headers.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "reth_downloaders_headers_in_flight_requests{instance=~\"$instance\"}",
     "legendFormat": "In flight requests"
    },
    {
     "expr": "reth_network_connected_peers{instance=~\"$instance\"}",
     "legendFormat": "Connected peers"
    }
   ]
  },
  { "title": "Downloader: Bodies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 }, "repeat": "instance" },
  {
   "title": "I/O",
   "type": "timeseries",
   "description": "The internal state of the headers downloader: the number of downloaded headers, and the number of headers sent to the header stage.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "reth_downloaders_bodies_total_downloaded{instance=~\"$instance\"}",
     "legendFormat": "Downloaded"
    },
    {
     "expr": "reth_downloaders_bodies_total_flushed{instance=~\"$instance\"}",
     "legendFormat": "Flushed"
    },
    {
     "expr": "rate(reth_downloaders_bodies_total_flushed{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Flushed/s"
    },
    {
     "expr": "rate(reth_downloaders_bodies_total_downloaded{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Downloaded/s"
    },
    {
     "expr": "reth_downloaders_bodies_buffered_responses{instance=~\"$instance\"}",
     "legendFormat": "Buffered responses"
    },
    {
     "expr": "reth_downloaders_bodies_buffered_blocks{instance=~\"$instance\"}",
     "legendFormat": "Buffered blocks"
    },
    {
     "expr": "reth_downloaders_bodies_queued_blocks{instance=~\"$instance\"}",
     "legendFormat": "Queued blocks"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Internal errors in the bodies downloader. These are expected to happen from time to time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(reth_downloaders_bodies_timeout_errors{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Request timed out"
    },
    {
     "expr": "rate(reth_downloaders_bodies_unexpected_errors{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Unexpected error"
    },
    {
     "expr": "rate(reth_downloaders_bodies_validation_errors{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Invalid response"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "The number of connected peers and in-progress requests for bodies.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "targets": [
    {
     "expr": "reth_downloaders_bodies_in_flight_requests{instance=~\"$instance\"}",
     "legendFormat": "In flight requests"
    },
    {
     "expr": "reth_network_connected_peers{instance=~\"$instance\"}",
     "legendFormat": "Connected peers"
    }
   ]
  },
  {
   "title": "Downloader buffer",
   "type": "timeseries",
   "description": "The number of blocks and size in bytes of those blocks",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "reth_downloaders_bodies_buffered_blocks_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "Buffered blocks size "
    },
    {
     "expr": "reth_downloaders_bodies_buffered_blocks{instance=~\"$instance\"}",
     "legendFormat": "Buffered blocks"
    }
   ]
  },
  {
   "title": "Block body response sizes",
   "type": "timeseries",
   "description": "The number of blocks in a request and size in bytes of those block responses",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "reth_downloaders_bodies_response_response_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "Response size"
    },
    {
     "expr": "reth_downloaders_bodies_response_response_length{instance=~\"$instance\"}",
     "legendFormat": "Individual response length (number of bodies in response)"
    },
    {
     "expr": "reth_downloaders_bodies_response_response_size_bytes / reth_downloaders_bodies_response_response_length{instance=~\"$instance\"}",
     "legendFormat": "Mean body size in response"
    }
   ]
  },
  { "title": "Blockchain Tree", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 137 }, "repeat": "instance" },
  {
   "title": "Canonical chain height",
   "type": "timeseries",
   "description": "The block number of the tip of the canonical chain from the blockchain tree.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 138 },
   "targets": [
    {
     "expr": "reth_blockchain_tree_canonical_chain_height{instance=~\"$instance\"}",
     "legendFormat": "Canonical chain height"
    }
   ]
  },
  {
   "title": "Block buffer blocks",
   "type": "timeseries",
   "description": "Total number of blocks in the tree's block buffer",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 138 },
   "targets": [
    {
     "expr": "reth_blockchain_tree_block_buffer_blocks{instance=~\"$instance\"}",
     "legendFormat": "Buffered blocks"
    }
   ]
  },
  {
   "title": "Sidechains",
   "type": "timeseries",
   "description": "Total number of sidechains in the blockchain tree",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 146 },
   "targets": [
    {
     "expr": "reth_blockchain_tree_sidechains{instance=~\"$instance\"}",
     "legendFormat": "Total number of sidechains"
    }
   ]
  },
  {
   "title": "Canonical Commit Latency time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(reth_consensus_engine_beacon_make_canonical_committed_latency_sum{instance=~\"$instance\"}[$__rate_interval]) / rate(reth_consensus_engine_beacon_make_canonical_committed_latency_count{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Reorg Depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "reth_blockchain_tree_latest_reorg_depth{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Engine API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 162 }, "repeat": "instance" },
  {
   "title": "Active block downloads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 163 },
   "targets": [
    {
     "expr": "reth_consensus_engine_beacon_active_block_downloads{instance=~\"$instance\"}",
     "legendFormat": "Active block downloads"
    }
   ]
  },
  {
   "title": "Engine API messages",
   "type": "timeseries",
   "description": "Engine API messages received by the CL, either engine_newPayload or engine_forkchoiceUpdated",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 163 },
   "targets": [
    {
     "expr": "reth_consensus_engine_beacon_forkchoice_updated_messages{instance=~\"$instance\"}",
     "legendFormat": "Forkchoice updated messages"
    },
    {
     "expr": "reth_consensus_engine_beacon_new_payload_messages{instance=~\"$instance\"}",
     "legendFormat": "New payload messages"
    }
   ]
  },
  {
   "title": "Pipeline runs",
   "type": "timeseries",
   "description": "Total pipeline runs triggered by the sync controller",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 171 },
   "targets": [
    {
     "expr": "reth_consensus_engine_beacon_pipeline_runs{instance=~\"$instance\"}",
     "legendFormat": "Pipeline runs"
    }
   ]
  },
  {
   "title": "Engine API newPayload Latency",
   "type": "timeseries",
   "description": "Latency histogram for the engine_newPayload RPC API",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_engine_rpc_new_payload_v1{instance=~\"$instance\", quantile=\"0\"}",
     "legendFormat": "engine_newPayloadV1 min"
    },
    {
     "expr": "reth_engine_rpc_new_payload_v1{instance=~\"$instance\", quantile=\"0.5\"}",
     "legendFormat": "engine_newPayloadV1 p50"
    },
    {
     "expr": "reth_engine_rpc_new_payload_v1{instance=~\"$instance\", quantile=\"0.9\"}",
     "legendFormat": "engine_newPayloadV1 p90"
    },
    {
     "expr": "reth_engine_rpc_new_payload_v1{instance=~\"$instance\", quantile=\"0.95\"}",
     "legendFormat": "engine_newPayloadV1 p95"
    },
    {
     "expr": "reth_engine_rpc_new_payload_v1{instance=~\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "engine_newPayloadV1 p99"
    },
    {
     "expr": "reth_engine_rpc_new_payload_v2{instance=~\"$instance\", quantile=\"0\"}",
     "legendFormat": "engine_newPayloadV2 min"
    },
    {
     "expr": "reth_engine_rpc_new_payload_v2{instance=~\"$instance\", quantile=\"0.5\"}",
     "legendFormat": "engine_newPayloadV2 p50"
    },
    {
     "expr": "reth_engine_rpc_new_payload_v2{instance=~\"$instance\", quantile=\"0.9\"}",
     "legendFormat": "engine_newPayloadV2 p90"
    },
    {
     "expr": "reth_engine_rpc_new_payload_v2{instance=~\"$instance\", quantile=\"0.95\"}",
     "legendFormat": "engine_newPayloadV2 p95"
    },
    {
     "expr": "reth_engine_rpc_new_payload_v2{instance=~\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "engine_newPayloadV2 p99"
    },
    {
     "expr": "reth_engine_rpc_new_payload_v3{instance=~\"$instance\", quantile=\"0\"}",
     "legendFormat": "engine_newPayloadV3 min"
    },
    {
     "expr": "reth_engine_rpc_new_payload_v3{instance=~\"$instance\", quantile=\"0.5\"}",
     "legendFormat": "engine_newPayloadV3 p50"
    },
    {
     "expr": "reth_engine_rpc_new_payload_v3{instance=~\"$instance\", quantile=\"0.9\"}",
     "legendFormat": "engine_newPayloadV3 p90"
    },
    {
     "expr": "reth_engine_rpc_new_payload_v3{instance=~\"$instance\", quantile=\"0.95\"}",
     "legendFormat": "engine_newPayloadV3 p95"
    },
    {
     "expr": "reth_engine_rpc_new_payload_v3{instance=~\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "engine_newPayloadV3 p99"
    }
   ]
  },
  {
   "title": "Engine API forkchoiceUpdated Latency",
   "type": "timeseries",
   "description": "Latency histogram for the engine_forkchoiceUpdated RPC API",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_engine_rpc_fork_choice_updated_v1{instance=~\"$instance\", quantile=\"0\"}",
     "legendFormat": "engine_forkchoiceUpdatedV1 min"
    },
    {
     "expr": "reth_engine_rpc_fork_choice_updated_v1{instance=~\"$instance\", quantile=\"0.5\"}",
     "legendFormat": "engine_forkchoiceUpdatedV1 p50"
    },
    {
     "expr": "reth_engine_rpc_fork_choice_updated_v1{instance=~\"$instance\", quantile=\"0.9\"}",
     "legendFormat": "engine_forkchoiceUpdatedV1 p90"
    },
    {
     "expr": "reth_engine_rpc_fork_choice_updated_v1{instance=~\"$instance\", quantile=\"0.95\"}",
     "legendFormat": "engine_forkchoiceUpdatedV1 p95"
    },
    {
     "expr": "reth_engine_rpc_fork_choice_updated_v1{instance=~\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "engine_forkchoiceUpdatedV1 p99"
    },
    {
     "expr": "reth_engine_rpc_fork_choice_updated_v2{instance=~\"$instance\", quantile=\"0\"}",
     "legendFormat": "engine_forkchoiceUpdatedV2 min"
    },
    {
     "expr": "reth_engine_rpc_fork_choice_updated_v2{instance=~\"$instance\", quantile=\"0.5\"}",
     "legendFormat": "engine_forkchoiceUpdatedV2 p50"
    },
    {
     "expr": "reth_engine_rpc_fork_choice_updated_v2{instance=~\"$instance\", quantile=\"0.9\"}",
     "legendFormat": "engine_forkchoiceUpdatedV2 p90"
    },
    {
     "expr": "reth_engine_rpc_fork_choice_updated_v2{instance=~\"$instance\", quantile=\"0.95\"}",
     "legendFormat": "engine_forkchoiceUpdatedV2 p95"
    },
    {
     "expr": "reth_engine_rpc_fork_choice_updated_v2{instance=~\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "engine_forkchoiceUpdatedV2 p99"
    },
    {
     "expr": "reth_engine_rpc_fork_choice_updated_v3{instance=~\"$instance\", quantile=\"0\"}",
     "legendFormat": "engine_forkchoiceUpdatedV3 min"
    },
    {
     "expr": "reth_engine_rpc_fork_choice_updated_v3{instance=~\"$instance\", quantile=\"0.5\"}",
     "legendFormat": "engine_forkchoiceUpdatedV3 p50"
    },
    {
     "expr": "reth_engine_rpc_fork_choice_updated_v3{instance=~\"$instance\", quantile=\"0.9\"}",
     "legendFormat": "engine_forkchoiceUpdatedV3 p90"
    },
    {
     "expr": "reth_engine_rpc_fork_choice_updated_v3{instance=~\"$instance\", quantile=\"0.95\"}",
     "legendFormat": "engine_forkchoiceUpdatedV3 p95"
    },
    {
     "expr": "reth_engine_rpc_fork_choice_updated_v3{instance=~\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "engine_forkchoiceUpdatedV3 p99"
    }
   ]
  },
  {
   "title": "Engine API getPayloadBodies Latency",
   "type": "timeseries",
   "description": "Latency histograms for the engine_getPayloadBodiesByHashV1 and engine_getPayloadBodiesByRangeV1 RPC APIs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_engine_rpc_get_payload_bodies_by_hash_v1{instance=~\"$instance\", quantile=\"0\"}",
     "legendFormat": "engine_getPayloadBodiesByHashV1 min"
    },
    {
     "expr": "reth_engine_rpc_get_payload_bodies_by_hash_v1{instance=~\"$instance\", quantile=\"0.5\"}",
     "legendFormat": "engine_getPayloadBodiesByHashV1 p50"
    },
    {
     "expr": "reth_engine_rpc_get_payload_bodies_by_hash_v1{instance=~\"$instance\", quantile=\"0.9\"}",
     "legendFormat": "engine_getPayloadBodiesByHashV1 p90"
    },
    {
     "expr": "reth_engine_rpc_get_payload_bodies_by_hash_v1{instance=~\"$instance\", quantile=\"0.95\"}",
     "legendFormat": "engine_getPayloadBodiesByHashV1 p95"
    },
    {
     "expr": "reth_engine_rpc_get_payload_bodies_by_hash_v1{instance=~\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "engine_getPayloadBodiesByHashV1 p99"
    },
    {
     "expr": "reth_engine_rpc_get_payload_bodies_by_range_v1{instance=~\"$instance\", quantile=\"0\"}",
     "legendFormat": "engine_getPayloadBodiesByRangeV1 min"
    },
    {
     "expr": "reth_engine_rpc_get_payload_bodies_by_range_v1{instance=~\"$instance\", quantile=\"0.5\"}",
     "legendFormat": "engine_getPayloadBodiesByRangeV1 p50"
    },
    {
     "expr": "reth_engine_rpc_get_payload_bodies_by_range_v1{instance=~\"$instance\", quantile=\"0.9\"}",
     "legendFormat": "engine_getPayloadBodiesByRangeV1 p90"
    },
    {
     "expr": "reth_engine_rpc_get_payload_bodies_by_range_v1{instance=~\"$instance\", quantile=\"0.95\"}",
     "legendFormat": "engine_getPayloadBodiesByRangeV1 p95"
    },
    {
     "expr": "reth_engine_rpc_get_payload_bodies_by_range_v1{instance=~\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "engine_getPayloadBodiesByRangeV1 p99"
    }
   ]
  },
  { "title": "State Trie", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 187 } },
  {
   "title": "Trie Root Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 188 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_trie_duration_seconds{instance=\"$instance\",quantile=~\"(0.5|0.9|0.99)\"}",
     "legendFormat": "{{type}} root p{{quantile}}"
    }
   ]
  },
  {
   "title": "Trie Nodes Added",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 188 },
   "targets": [
    {
     "expr": "reth_trie_branches_added{instance=\"$instance\",quantile=~\"(0.5|0.9|0.99)\"}",
     "legendFormat": "{{type}} branch nodes p{{quantile}}"
    },
    {
     "expr": "reth_trie_leaves_added{instance=\"$instance\",quantile=~\"(0.5|0.9|0.99)\"}",
     "legendFormat": "{{type}} leaves added p{{quantile}}"
    }
   ]
  },
  { "title": "Payload Builder", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 196 }, "repeat": "instance" },
  {
   "title": "Active Jobs",
   "type": "timeseries",
   "description": "Number of active jobs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 197 },
   "targets": [
    {
     "expr": "reth_payloads_active_jobs{instance=~\"$instance\"}",
     "legendFormat": "Active Jobs"
    }
   ]
  },
  {
   "title": "Initiated Jobs",
   "type": "timeseries",
   "description": "Total number of initiated jobs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 197 },
   "targets": [
    {
     "expr": "reth_payloads_initiated_jobs{instance=~\"$instance\"}",
     "legendFormat": "Initiated Jobs"
    }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "timeseries",
   "description": "Total number of failed jobs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 205 },
   "targets": [
    {
     "expr": "reth_payloads_failed_jobs{instance=~\"$instance\"}",
     "legendFormat": "Failed Jobs"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 213 } },
  {
   "title": "Jemalloc Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 214 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "reth_jemalloc_active{instance=~\"$instance\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "reth_jemalloc_allocated{instance=~\"$instance\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "reth_jemalloc_mapped{instance=~\"$instance\"}",
     "legendFormat": "Mapped"
    },
    {
     "expr": "reth_jemalloc_metadata{instance=~\"$instance\"}",
     "legendFormat": "Metadata"
    },
    {
     "expr": "reth_jemalloc_resident{instance=~\"$instance\"}",
     "legendFormat": "Resident"
    },
    {
     "expr": "reth_jemalloc_retained{instance=~\"$instance\"}",
     "legendFormat": "Retained"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 214 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "reth_process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "Resident"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "100% = 1 core",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 222 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(reth_process_cpu_seconds_total{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Process"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 222 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "reth_process_open_fds{instance=~\"$instance\"}",
     "legendFormat": "Open"
    }
   ]
  },
  { "title": "Pruning", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 230 } },
  {
   "title": "Pruner duration, total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 231 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(reth_pruner_duration_seconds_sum{instance=~\"$instance\"}[$__rate_interval]) / rate(reth_pruner_duration_seconds_count{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pruner duration, per segment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 231 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(reth_pruner_segments_duration_seconds_sum{instance=~\"$instance\"}[$__rate_interval]) / rate(reth_pruner_segments_duration_seconds_count{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{segment}}"
    }
   ]
  },
  {
   "title": "Highest pruned block, per segment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 239 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "reth_pruner_segments_highest_pruned_block{instance=~\"$instance\"}",
     "legendFormat": "{{segment}}"
    }
   ]
  },
  { "title": "RPC server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 247 } },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 248 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(reth_rpc_server_connections_connections_opened_total{instance=~\"$instance\"} - reth_rpc_server_connections_connections_closed_total{instance=~\"$instance\"}) by (transport)",
     "legendFormat": "{{transport}}"
    }
   ]
  },
  {
   "title": "Request Latency time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 248 },
   "targets": [
    {
     "expr": "avg(max_over_time(reth_rpc_server_connections_request_time_seconds{instance=~\"$instance\"}[$__rate_interval]) > 0) by (quantile)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maximum call latency per method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 256 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(max_over_time(reth_rpc_server_calls_time_seconds{instance=~\"$instance\"}[$__rate_interval])) by (method) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Call Latency time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 256 },
   "targets": [
    {
     "expr": "avg(max_over_time(reth_rpc_server_calls_time_seconds{instance=~\"$instance\"}[$__rate_interval]) > 0) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "RPC Cache Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 264 },
   "targets": [
    {
     "expr": "reth_rpc_eth_cache_cached_count{instance=\"$instance\", cache=\"evm_env\"}",
     "legendFormat": "EVM environment cache cached items"
    },
    {
     "expr": "reth_rpc_eth_cache_queued_consumers_count{instance=\"$instance\", cache=\"receipts\"}",
     "legendFormat": "Receipts cache queued consumers"
    },
    {
     "expr": "reth_rpc_eth_cache_queued_consumers_count{instance=\"$instance\", cache=\"evm_env\"}",
     "legendFormat": "EVM environment cache queued consumers"
    },
    {
     "expr": "reth_rpc_eth_cache_queued_consumers_count{instance=\"$instance\", cache=\"blocks\"}",
     "legendFormat": "Block cache queued consumers"
    },
    {
     "expr": "reth_rpc_eth_cache_cached_count{instance=\"$instance\", cache=\"blocks\"}",
     "legendFormat": "Block cache cached items"
    },
    {
     "expr": "reth_rpc_eth_cache_cached_count{instance=\"$instance\", cache=\"receipts\"}",
     "legendFormat": "Receipts cache cached items"
    }
   ]
  },
  {
   "title": "RPC Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 264 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(reth_rpc_server_calls_successful_total{instance =~ \"$instance\"}[$__rate_interval])) by (method) > 0",
     "legendFormat": "{{method}}"
    }
   ]
  },
  { "title": "Execution Extensions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 272 } },
  {
   "title": "Total Notifications Sent",
   "type": "timeseries",
   "description": "The total number of canonical state notifications sent to an ExEx.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 273 },
   "targets": [
    {
     "expr": "reth_exex_notifications_sent_total{instance=~\"$instance\"}",
     "legendFormat": "Total Notifications Sent"
    }
   ]
  },
  {
   "title": "Total Events Sent",
   "type": "timeseries",
   "description": "The total number of events an ExEx has sent to the manager.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 273 },
   "targets": [
    {
     "expr": "reth_exex_events_sent_total{instance=~\"$instance\"}",
     "legendFormat": "Total Events Sent"
    }
   ]
  },
  {
   "title": "Current and Max Capacity",
   "type": "timeseries",
   "description": "Current and Max capacity of the internal state notifications buffer.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 281 },
   "targets": [
    {
     "expr": "reth_exex_manager_current_capacity{instance=~\"$instance\"}",
     "legendFormat": "Current size"
    },
    {
     "expr": "max_over_time(reth_exex_manager_max_capacity{instance=~\"$instance\"}[1h])",
     "legendFormat": "Max size"
    }
   ]
  },
  {
   "title": "Buffer Size",
   "type": "timeseries",
   "description": "Current size of the internal state notifications buffer.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 281 },
   "targets": [
    {
     "expr": "reth_exex_manager_buffer_size{instance=~\"$instance\"}",
     "legendFormat": "Max size"
    }
   ]
  },
  {
   "title": "Number of ExExs",
   "type": "stat",
   "description": "Number of ExExs on the node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 289 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_exex_manager_num_exexs{instance=~\"$instance\"}",
     "legendFormat": "Number of ExExs"
    }
   ]
  },
  { "title": "Eth Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 297 } },
  {
   "title": "Headers Requests Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 298 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(reth_network_eth_headers_requests_received_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Headers Requests/s"
    }
   ]
  },
  {
   "title": "Receipts Requests Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 298 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(reth_network_eth_receipts_requests_received_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Receipts Requests/s"
    }
   ]
  },
  {
   "title": "Bodies Requests Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 306 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(reth_network_eth_bodies_requests_received_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Bodies Requests/s"
    }
   ]
  },
  {
   "title": "Node Data Requests Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 306 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(reth_network_eth_node_data_requests_received_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Node Data Requests/s"
    }
   ]
  }
 ]
}