# Use regtest as default
regtest=1

# Options for mainnet
[main]

# Options for testnet
[test]

# Options for signet
[signet]

# Options for regtest
[regtest]
rpcuser=test123
rpcpassword=test123
server=1
txindex=1
fallbackfee=0.00001
rpcallowip=127.0.0.1
zmqpubrawblock=tcp://127.0.0.1:28332
zmqpubrawtx=tcp://127.0.0.1:28333
