name: Build, Tag, and Deploy Docker Reth Node Image to GCP

on:
  push:
    branches:
      - sandbox

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Log in to Google Container Registry
        run: |
          echo ${{ secrets.GCR_SERVICE_ACCOUNT_KEY }} | docker login -u _json_key --password-stdin https://us-central1-docker.pkg.dev
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCR_SERVICE_ACCOUNT_KEY }}

      - name: Build Docker image
        run: |
          docker build --platform linux/amd64 -t botanix_sandbox -f Dockerfile.testnet .
        working-directory: ./

      - name: Tag Docker image
        run: |
          docker tag botanix_sandbox:latest us-central1-docker.pkg.dev/botanix-391913/botanix-sandbox-node/botanix_sandbox:latest

      - name: Push Docker image to Google Container Registry
        run: |
          docker push us-central1-docker.pkg.dev/botanix-391913/botanix-sandbox-node/botanix_sandbox:latest
