name: Build, Tag, and Deploy Botanix Testnet v1

on:
  pull_request:
    branches:
      - main
    types: [closed]
    
jobs:
  build_and_deploy_btc_server:
    runs-on: botanix-actions-runner
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linx/arm64,linux/arm/v7

      - name: Build Docker image
        run: |
          docker build --platform linux/amd64 -t botanix_testnet_btc_server_v1 -f Dockerfile.btc_server .
        working-directory: ./

      - name: Tag Docker image
        run: |
          cat /etc/gcp/sa_credentials.json | docker login -u _json_key --password-stdin https://us-central1-docker.pkg.dev
          docker tag botanix_testnet_btc_server_v1:latest us-central1-docker.pkg.dev/botanix-391913/botanix-testnet-btc-server-v1/botanix-btc-server-v1:latest

      - name: Push Docker image to Google Container Registry
        run: |
          docker push us-central1-docker.pkg.dev/botanix-391913/botanix-testnet-btc-server-v1/botanix-btc-server-v1:latest

  build_and_deploy_poa_node:
    runs-on: botanix-actions-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.6.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build --platform linux/amd64 -t botanix_testnet_v1 -f Dockerfile .
        working-directory: ./

      - name: Tag Docker image
        run: |
          cat /etc/gcp/sa_credentials.json | docker login -u _json_key --password-stdin https://us-central1-docker.pkg.dev
          docker tag botanix_testnet_v1:latest us-central1-docker.pkg.dev/botanix-391913/botanix-testnet-node-v1/botanix-poa-node:latest

      - name: Push Docker image to Google Container Registry
        run: |
          docker push us-central1-docker.pkg.dev/botanix-391913/botanix-testnet-node-v1/botanix-poa-node:latest
  
  dispatch:
    runs-on: botanix-actions-runner
    name: Dispatch to Botanix Testnet v1 internal deployment
    needs: [build_and_deploy_btc_server, build_and_deploy_poa_node]
    steps: 
      - name: Dispatch event
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.DEPLOYMENT_TOKEN }}" \
            -d '{"event_type": "deploy-testnet-v1"}' \
            https://api.github.com/repos/botanix-labs/internal-releases/dispatches

        
     