name: Build, Tag, and Deploy Botanix Images

on:
  push:
    tags:
      - v*

jobs:
  build_and_deploy_btc_server:
    runs-on: botanix-actions-runner
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Docker
        uses: docker/setup-buildx-action@v4
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      - name: gcloud auth
        uses: google-github-actions/auth@v3
        with:
          project_id: botanix-391913
          workload_identity_provider: projects/1091390741689/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions-sa@botanix-391913.iam.gserviceaccount.com

      - name: gcloud setup
        uses: google-github-actions/setup-gcloud@v3
        with:
          project_id: botanix-391913

      - name: Build Docker image
        run: |
          docker build \
            --platform linux/amd64 \
            -t botanix_btc_server \
            -f Dockerfile \
            --build-arg PACKAGE=btc-server \
            --build-arg BIN=btc-server \
            .
        working-directory: ./

      - name: Get short SHA
        id: sha
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Get tag
        id: tag
        run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Configure Docker cred-helper
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=/var/run/artifact-creds/sa_json
          gcloud --quiet auth configure-docker us-central1-docker.pkg.dev
          
      - name: Tag Docker images for testnet and mainnet
        run: |
          # Tag for testnet registry
          docker tag botanix_btc_server:latest us-central1-docker.pkg.dev/botanix-391913/botanix-testnet-btc-server-v1/botanix-btc-server-v1:${{ steps.sha.outputs.short_sha }}
          docker tag botanix_btc_server:latest us-central1-docker.pkg.dev/botanix-391913/botanix-testnet-btc-server-v1/botanix-btc-server-v1:${{ steps.tag.outputs.tag }}
          docker tag botanix_btc_server:latest us-central1-docker.pkg.dev/botanix-391913/botanix-testnet-btc-server-v1/botanix-btc-server-v1:latest
          
          # Tag for mainnet registry
          docker tag botanix_btc_server:latest us-central1-docker.pkg.dev/botanix-391913/botanix-mainnet-btc-server/botanix-btc-server:${{ steps.sha.outputs.short_sha }}
          docker tag botanix_btc_server:latest us-central1-docker.pkg.dev/botanix-391913/botanix-mainnet-btc-server/botanix-btc-server:${{ steps.tag.outputs.tag }}
          docker tag botanix_btc_server:latest us-central1-docker.pkg.dev/botanix-391913/botanix-mainnet-btc-server/botanix-btc-server:latest

      - name: Push Docker images
        run: |
          # Push to testnet registry
          docker push us-central1-docker.pkg.dev/botanix-391913/botanix-testnet-btc-server-v1/botanix-btc-server-v1:${{ steps.sha.outputs.short_sha }}
          docker push us-central1-docker.pkg.dev/botanix-391913/botanix-testnet-btc-server-v1/botanix-btc-server-v1:${{ steps.tag.outputs.tag }}
          docker push us-central1-docker.pkg.dev/botanix-391913/botanix-testnet-btc-server-v1/botanix-btc-server-v1:latest
          
          # Push to mainnet registry
          docker push us-central1-docker.pkg.dev/botanix-391913/botanix-mainnet-btc-server/botanix-btc-server:${{ steps.sha.outputs.short_sha }}
          docker push us-central1-docker.pkg.dev/botanix-391913/botanix-mainnet-btc-server/botanix-btc-server:${{ steps.tag.outputs.tag }}
          docker push us-central1-docker.pkg.dev/botanix-391913/botanix-mainnet-btc-server/botanix-btc-server:latest

  build_and_deploy_reth_node:
    runs-on: botanix-actions-runner
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Cosign
        uses: sigstore/cosign-installer@v4.0.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v4

      - name: Build Docker image
        run: |
          docker build \
            --platform linux/amd64 \
            -t botanix_reth \
            -f Dockerfile \
            --build-arg PACKAGE=reth \
            --build-arg BIN=reth \
            .
        working-directory: ./

      - name: Get short SHA
        id: sha
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: gcloud auth
        uses: google-github-actions/auth@v3
        with:
          project_id: botanix-391913
          workload_identity_provider: projects/1091390741689/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions-sa@botanix-391913.iam.gserviceaccount.com

      - name: gcloud setup
        uses: google-github-actions/setup-gcloud@v3
        with:
          project_id: botanix-391913

      - name: Get tag
        id: tag
        run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Configure Docker cred-helper
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=/var/run/artifact-creds/sa_json
          gcloud --quiet auth configure-docker us-central1-docker.pkg.dev
          
      - name: Tag Docker images for testnet and mainnet
        run: |
          # Tag for testnet registry
          docker tag botanix_reth:latest us-central1-docker.pkg.dev/botanix-391913/botanix-testnet-node-v1/botanix-poa-node:${{ steps.sha.outputs.short_sha }}
          docker tag botanix_reth:latest us-central1-docker.pkg.dev/botanix-391913/botanix-testnet-node-v1/botanix-poa-node:${{ steps.tag.outputs.tag }}
          docker tag botanix_reth:latest us-central1-docker.pkg.dev/botanix-391913/botanix-testnet-node-v1/botanix-poa-node:latest
          
          # Tag for mainnet registry
          docker tag botanix_reth:latest us-central1-docker.pkg.dev/botanix-391913/botanix-mainnet-node/botanix-reth:${{ steps.sha.outputs.short_sha }}
          docker tag botanix_reth:latest us-central1-docker.pkg.dev/botanix-391913/botanix-mainnet-node/botanix-reth:${{ steps.tag.outputs.tag }}
          docker tag botanix_reth:latest us-central1-docker.pkg.dev/botanix-391913/botanix-mainnet-node/botanix-reth:latest

      - name: Push Docker images
        run: |
          # Push to testnet registry
          docker push us-central1-docker.pkg.dev/botanix-391913/botanix-testnet-node-v1/botanix-poa-node:${{ steps.sha.outputs.short_sha }}
          docker push us-central1-docker.pkg.dev/botanix-391913/botanix-testnet-node-v1/botanix-poa-node:${{ steps.tag.outputs.tag }}
          docker push us-central1-docker.pkg.dev/botanix-391913/botanix-testnet-node-v1/botanix-poa-node:latest
          
          # Push to mainnet registry
          docker push us-central1-docker.pkg.dev/botanix-391913/botanix-mainnet-node/botanix-reth:${{ steps.sha.outputs.short_sha }}
          docker push us-central1-docker.pkg.dev/botanix-391913/botanix-mainnet-node/botanix-reth:${{ steps.tag.outputs.tag }}
          docker push us-central1-docker.pkg.dev/botanix-391913/botanix-mainnet-node/botanix-reth:latest

  dispatch_testnet:
    runs-on: botanix-actions-runner
    name: Dispatch to Botanix Testnet v1 internal deployment
    needs: [build_and_deploy_btc_server, build_and_deploy_reth_node]
    steps:
      - name: Dispatch event
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.DEPLOYMENT_TOKEN }}" \
            -d '{"event_type": "deploy-testnet-v1"}' \
            https://api.github.com/repos/botanix-labs/internal-releases/dispatches

