name: Docker Build Test for BTC Server

on:
  pull_request:
    branches:
      - main
    types: [opened, closed]

jobs:
  build_and_deploy:
    runs-on: image-builder

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          echo "IMAGE_TAG=$GITHUB_SHA-$GITHUB_RUN_ID-$GITHUB_RUN_ATTEMPT" >> $GITHUB_ENV && echo $IMAGE_TAG
          docker build --platform linux/amd64 -t botanix_testnet_btc_server_v1 -f Dockerfile.btc_server .
          docker tag botanix_testnet_btc_server_v1:latest us-central1-docker.pkg.dev/botanix-391913/botanix-testnet-btc-server-v1/botanix-btc-server-v1:$IMAGE_TAG
        working-directory: ./



