# Runs integration tests.
name: Botanix Integration Tests

on:
  pull_request:
  merge_group:
    branches: [main, feature/poA-consensus]
  push:
    branches: [feature/poA-consensus]

env:
  CARGO_TERM_COLOR: always
  SEED: rustethereumethereumrust
  BITCOIND_NETWORK: regtest
  BITCOIND_URL: http:/localhost:18443
  BITCOIND_USER: botanix-ci-user
  BITCOIND_PWD: ${{ secrets.BITCOIND_PWD }}
  JWT_DIR: "/home/runner/actions-runner/_work/Macbeth/Macbeth/bin/test-suite/jwt"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  e2e:
    name: test / e2e
    runs-on: botanix-actions-runner-vm-1
    env:
      RUST_BACKTRACE: 1
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
          toolchain: stable
      
      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - run: rustup toolchain install stable --profile minimal

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          cache-all-crates: true
          env-vars: |
            CARGO_HOME="/home/runner/.cargo"

      - name: Compile btc-server
        run: |
          cd ./bin/btc-server && \
          cargo build --bin btc-server && \
          echo "Bitcoin server compiled successfully!"

      - name: Compile poa-node
        run: |
          cargo build --bin reth && \
          echo "Poa node compiled successfully!"

      - name: Run e2e tests
        run: |
          set -e
          set -o pipefail
          chmod +x test_runner.sh
          bash test_runner.sh
          sleep 1500
          echo "e2e tests completed successfully!"


  sync:
    name: sync / 100k blocks
    # Only run sync tests in merge groups
    if: github.event_name == 'merge_group'
    runs-on:
      group: Reth
    env:
      RUST_LOG: info,sync=error
      RUST_BACKTRACE: 1
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Run sync
        run: |
          cargo run --release --features asm-keccak,jemalloc,min-error-logs --bin reth \
            -- node \
            --debug.tip 0x91c90676cab257a59cd956d7cb0bceb9b1a71d79755c23c7277a0697ccfaf8c4 \
            --debug.max-block 100000 \
            --debug.terminate
      - name: Verify the target block hash
        run: |
          cargo run --release --bin reth \
            -- db get static-file headers 100000 \
            | grep 0x91c90676cab257a59cd956d7cb0bceb9b1a71d79755c23c7277a0697ccfaf8c4


          