# Runs integration tests.
name: Botanix Integration Tests

on:
  pull_request:
  merge_group:
    branches: [main]
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  SEED: rustethereumethereumrust
  JWT_DIR: "/home/runner/actions-runner/_work/Macbeth/Macbeth/bin/test-suite/jwt"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  e2e:
    name: test / e2e
    runs-on:
      group: macbeth
    env:
      RUST_BACKTRACE: 1
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
          toolchain: stable

      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Install killall
        run: sudo apt-get install psmisc

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          cache-all-crates: true
          env-vars: |
            CARGO_HOME="/home/runner/.cargo"

      - name: Compile btc-server
        run: |
          cd ./bin/btc-server && \
          cargo build --features conflicting_input --bin btc-server && \
          echo "Bitcoin server compiled successfully!"

      - name: Compile poa-node
        run: |
          cargo build --bin reth && \
          echo "Poa node compiled successfully!"

      # Define individual steps for each test
      - name: Run dkg_flow
        run: |
          export TEST_TO_RUN="dkg_flow"
          make start-test-suite
          killall btc-server || true
          killall bitcoind || true

      - name: Run utxo_commitment
        run: |
          export TEST_TO_RUN="utxo_commitment"
          make start-test-suite
          killall btc-server || true
          killall bitcoind || true

      - name: Run signing_flow
        run: |
          export TEST_TO_RUN="signing_flow"
          make start-test-suite
          killall btc-server || true
          killall bitcoind || true

      - name: Run test_mempool_gossip
        run: |
          export TEST_TO_RUN="test_mempool_gossip"
          make start-test-suite
          killall btc-server || true
          killall bitcoind || true

      - name: Run utxo_sync
        run: |
          export TEST_TO_RUN="utxo_sync"
          make start-test-suite
          killall btc-server || true
          killall bitcoind || true

      - name: Run state_sync
        run: |
          export TEST_TO_RUN="state_sync"
          make start-test-suite
          killall btc-server || true
          killall bitcoind || true

      - name: Run frost_e2e_stable
        run: |
          export TEST_TO_RUN="frost_e2e_stable"
          make start-test-suite
          killall btc-server || true
          killall bitcoind || true

      - name: Run test_pegin_v1
        run: |
          export TEST_TO_RUN="test_pegin_v1"
          make start-test-suite
          killall btc-server || true
          killall bitcoind || true

      - name: Run invalid_pegin
        run: |
          export TEST_TO_RUN="invalid_pegin"
          make start-test-suite
          killall btc-server || true
          killall bitcoind || true

      - name: Run invalid_pegout
        run: |
          export TEST_TO_RUN="invalid_pegout"
          make start-test-suite
          killall btc-server || true
          killall bitcoind || true

      - name: Run block_builder
        run: |
          export TEST_TO_RUN="block_builder"
          make start-test-suite
          killall btc-server || true
          killall bitcoind || true

      - name: Run test_conflicting_input
        run: |
          export TEST_TO_RUN="test_conflicting_input"
          make start-test-suite
          killall btc-server || true
          killall bitcoind || true

      - name: Run test_round1_then_new_signing_session
        run: |
          export TEST_TO_RUN="test_round1_then_new_signing_session"
          make start-test-suite
          killall btc-server || true
          killall bitcoind || true

      - name: Run test_track_mempool
        run: |
          export TEST_TO_RUN="test_track_mempool"
          make start-test-suite
          killall btc-server || true
          killall bitcoind || true

      # ✅ Final success step if all tests pass
      - name: All tests passed!
        if: success()
        run: echo "✅ All tests completed successfully!"

  integration-success:
    name: integration success
    runs-on: ubuntu-latest
    if: always()
    needs: [e2e]
    timeout-minutes: 30
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
