# Runs integration tests.
name: Botanix Integration Tests

on:
  pull_request:
  merge_group:
    branches: [main]
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  SEED: rustethereumethereumrust
  JWT_DIR: "/home/runner/actions-runner/_work/Macbeth/Macbeth/bin/test-suite/jwt"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  e2e:
    name: test / e2e
    runs-on: 
      group: macbeth
    env:
      RUST_BACKTRACE: 1
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
          toolchain: stable

      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Install killall 
        run: sudo apt-get install psmisc

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          cache-all-crates: true
          env-vars: |
            CARGO_HOME="/home/runner/.cargo"

      - name: Compile btc-server
        run: |
          cd ./bin/btc-server && \
          cargo build --features conflicting_input --bin btc-server && \
          echo "Bitcoin server compiled successfully!"

      - name: Compile poa-node
        run: |
          cargo build --bin reth && \
          echo "Poa node compiled successfully!"

      - name: Run e2e tests
        run: |
          set -e
          set -o pipefail
          chmod +x test_runner.sh
          bash test_runner.sh
          killall btc-server || true
          echo "e2e tests completed successfully!"

  integration-success:
    name: integration success
    runs-on: ubuntu-latest
    if: always()
    needs: [e2e]
    timeout-minutes: 30
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
