name: Lints

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - reopened
  merge_group:
    branches:
      - develop
      - hotfix
  push:
    branches:
      - main
      - develop
      - hotfix

permissions:
  contents: read
  pull-requests: write

env:
  CARGO_TERM_COLOR: always
  CLICOLOR: 1
  CI: true

jobs:
    # Commenting out for now, will re-enable in the future
    # clippy-binaries:
    #   name: clippy / ethereum
    #   runs-on: ubuntu-latest
    #   timeout-minutes: 30
    #   steps:
    #     - uses: actions/checkout@v6
    #     - name: Install Protobuf Compiler
    #       run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
    #     - uses: dtolnay/rust-toolchain@clippy
    #     - uses: Swatinem/rust-cache@v2
    #       with:
    #         cache-on-failure: true
    #         cache-all-crates: true
    #     - run:
    #         cargo +nightly clippy --bin reth --workspace --features "ethereum asm-keccak jemalloc jemalloc-prof min-error-logs min-warn-logs min-info-logs min-debug-logs min-trace-logs"
    #       env:
    #         RUSTFLAGS: -D warnings

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
      - name: Install Protobuf Compiler
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - uses: dtolnay/rust-toolchain@clippy
        with:
          components: rustfmt, clippy
          toolchain: 1.85.0
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          cache-all-crates: true
      - uses: clechasseur/rs-clippy-check@286fd9545eb133adad54b4af34bcb642e266ddd1
        with:
          args: -p reth-authority-consensus -p reth-network --lib --tests --benches --all-features --locked -- --no-deps

  crate-checks:
    name: Crate checks
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      # We should set it here so the rust-cache action can see it too
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@cargo-hack
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          cache-all-crates: true
      - name: Install Protobuf Compiler
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - run: cargo check --workspace

  lockfile:
    name: Cargo lock freshness
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
          toolchain: stable
      - run: cargo update --workspace --locked

  # pre-commit:
  #   name: Pre-commit
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v6

  #     - name: Check workflow files
  #       uses: docker://rhysd/actionlint:latest
  #       env:
  #         SHELLCHECK_OPTS: --exclude=SC2046,SC2162,SC2116,SC2004,SC2002,SC2086,SC2129
  #       with:
  #         args: -color

  #     - uses: dtolnay/rust-toolchain@nightly
  #       with:
  #         components: rustfmt, clippy
  #         toolchain: nightly

  #     - name: Install Node.js
  #       uses: actions/setup-node@v6
  #       with:
  #         node-version: 20

  #     - uses: pnpm/action-setup@v4
  #       name: Install pnpm
  #       with:
  #         version: 9
  #         run_install: true

  #     - uses: actions/setup-python@v4
  #       with:
  #         python-version: 3.x

  #     - name: Run Pre Commit
  #       uses: pre-commit/action@v3.0.1

    # Commenting out for now, will re-enable in once we have a MSRV
    #   msrv:
    #     name: MSRV
    #     runs-on: botanix-actions-runner
    #     timeout-minutes: 60
    #     steps:
    #       - uses: actions/checkout@v6
    #       - name: Install Protobuf Compiler
    #         run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
    #       - uses: dtolnay/rust-toolchain@master
    #         with:
    #           toolchain: "1.77.2"  # MSRV
    #       - uses: Swatinem/rust-cache@v2
    #         with:
    #           cache-on-failure: true
    #           cache-all-crates: true
    #       - run: cargo build --bin reth --workspace
    #         env:
    #           RUSTFLAGS: -D warnings

    # Commenting out for now, will re-enable in the future
    # docs:
    #   name: docs
    #   runs-on: ubuntu-latest
    #   timeout-minutes: 30
    #   steps:
    #     - uses: actions/checkout@v6
    #     - name: Install Protobuf Compiler
    #       run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
    #     - uses: dtolnay/rust-toolchain@nightly
    #     - uses: Swatinem/rust-cache@v2
    #       with:
    #         cache-on-failure: true
    #         cache-all-crates: true

    #     - run: cargo docs --document-private-items
    #       env:
    #  # Keep in sync with ./book.yml:jobs.build
    #  # This should only add `-D warnings`
    #         RUSTDOCFLAGS:
    #           --cfg docsrs --show-type-layout --generate-link-to-definition --enable-index-page
    #           -Zunstable-options -D warnings

  # TODO: Why do we just format code without any checks?
  fmt:
    name: Project formatting
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy
          toolchain: nightly

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install Protobuf Compiler
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Install JS deps
        run: pnpm install --frozen-lockfile

      - name: Install cargo-sort
        run: cargo install cargo-sort

      - name: Format project
        run: make fmt

  rust-fmt:
    name: Rust formatting
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
          toolchain: nightly

      - name: Check formatting
        uses: clechasseur/rs-fmt-check@aed481830b6601bcddf260f4037ebe4b2443584e

  # cargo-verifications:
  #   name: Cargo verifications
  #   needs:
  #     - lockfile
  #     - codespell
  #     - grafana
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v6

  #     - uses: dtolnay/rust-toolchain@nightly
  #       with:
  #         components: rustfmt, clippy
  #         toolchain: nightly

  #     - name: Install Node.js
  #       uses: actions/setup-node@v6
  #       with:
  #         node-version: 20

  #     - uses: pnpm/action-setup@v4
  #       name: Install pnpm
  #       with:
  #         version: 9
  #         run_install: true

  #     - name: Install Protobuf Compiler
  #       run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

  #     - name: Lint project
  #       run: make lint

  codespell:
    name: Codespell
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
      - uses: codespell-project/actions-codespell@v2
        with:
          skip: "*.json"

  grafana:
    name: Grafana dashboard JSON validation
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
      - name: Check dashboard JSON with jq
        uses: sergeysova/jq-action@v2
        with:
          cmd: jq empty etc/grafana/dashboards/overview.json

  signed-commits:
    name: Signed commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Check commits are signed
        uses: 1Password/check-signed-commits-action@v1

  lint-success:
    name: All green
    runs-on: ubuntu-latest
    if: always()
    needs:
      - clippy
      - crate-checks
      - lockfile
      - fmt
      - rust-fmt
      - codespell
      - grafana
      - signed-commits
      # - cargo-verifications
    timeout-minutes: 30
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
